Assets/MyAsset/01. Scenes/Main Scene.unity, Assets/MyAsset/03. Script/Controller/SubLineController.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/UI/Controller/PatronageController.cs, Assets/MyAsset/03. Script/UI/Displayer/PanelDisplayer.cs, Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism1Branch.prefab, Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism2Branch.prefab, Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism3Branch.prefab, Assets/MyAsset/04. Prefab/Line/SubLine.prefab, Assets/MyAsset/06. Material/SubLineMaterial.mat, Assets/MyAsset/06. Material/SubLineMaterial.mat.meta, Assets/MyAsset/10. Shader.meta, Assets/MyAsset/10. Shader/dottedLine.shadergraph, Assets/MyAsset/10. Shader/dottedLine.shadergraph.meta, Assets/MyAsset/ClassDiagram1.cd, Assets/MyAsset/ClassDiagram1.cd.meta
[Feat]
보조선 실선에서 점선 + 셰이더 추가
[Fix]
일부 아이템 남은 사용 횟수 텍스트 크기가 다르던 문제 해결
=> Feat : Sub line | Fix : Item using count

Assets/IronSource.meta, Assets/IronSource/Editor.meta, Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta, Assets/Layer Lab.meta, Assets/Layer Lab/GUI-TheStone.meta, Assets/Layer Lab/GUI-TheStone/PSD,AI.meta, Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/LaserManager.cs
=> Feat : 데미지 로직 추가

Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Entity/Laser.cs
- 충돌 시 생성되는 레이저의 계층 변화하는 코드 추가
=> Feat : 프리즘 충돌 시 계층연산 추가

Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta, Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/LaserManager.cs
=> Fix :  Reset함수 수정

Assets/IronSource/Editor/IronSource_IntegrationManager.unitypackage.meta, Assets/Layer Lab/GUI-TheStone/PSD,AI/PSD,AI.unitypackage.meta, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs
=> Fix : 블럭 생성 로직 수정

Assets/MyAsset/09. Data/ItemProbability Data.asset
=> Adjust : 수치 조정

Assets/MyAsset/01. Scenes/Main Scene.unity, Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/LaserManager.cs
[Feat]
레이저 오브젝트 풀링 적용
버그 있는 것 같음
=> Feat : Laser pooling

Assets/MyAsset/01. Scenes/Main Scene.unity, Assets/MyAsset/03. Script/Controller/SubLineController.cs, Assets/MyAsset/03. Script/Controller/ToolbarController.cs, Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedItem.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/GameSettingManager.cs, ProjectSettings/ProjectSettings.asset
[Feat]
런쳐 보조선 중 반사각 표시하는 보조선 설치된 아이템 충돌 때는 표시 안함
[Fix]
설치한 아이템 위치 수정 중 보조선이 제대로 표시 안되던 문제 해결
=> Feat : Launcher second subline | Fix: Installed item pos

Assets/MyAsset/01. Scenes/Main Scene.unity, Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Manager/DataManager.cs, Assets/MyAsset/03. Script/Manager/ItemManager.cs, Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch4.prefab, Assets/MyAsset/04. Prefab/Item/AcquiredItem/PrismBranch4.prefab.meta, Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism4.prefab, Assets/MyAsset/04. Prefab/Item/DroppedItem/DroppedPrism4.prefab.meta, Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab, Assets/MyAsset/04. Prefab/Item/InstalledItem/Prism4Branch.prefab.meta, Assets/MyAsset/09. Data/ItemProbability Data.asset
[Feat]
4갈래 프리즘 추가
[Fix]
프리즘 종류 상관없이 충돌 시 받는 추가 에너지 양이 모두 같던 문제 해결
=> Feat : 4 branch prism | Fix : Item additional energy

Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs
=> Feat : 충돌 시 에너지 정지

Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Entity/Floor.cs, Assets/MyAsset/03. Script/Entity/Item/DroppedItem/DroppedEnergy.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/LaserManager.cs
- 에너지 소모 방식 수정 데미지 == 에너지  -> 지속시간 == 에너지
=> Feat : 게임 로직 수정

Assets/MyAsset/03. Script/Controller/SubLineController.cs, Assets/MyAsset/03. Script/Controller/ToolbarController.cs, Assets/MyAsset/03. Script/Data/BlockData.cs, Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Extension/ExtensionLayerMask.cs, Assets/MyAsset/03. Script/Extension/ExtensionLayerMask.cs.meta, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/RayManager.cs, Assets/MyAsset/03. Script/Test/TestAssetLaser.cs, Assets/MyAsset/09. Data/Block Data.asset, ProjectSettings/ProjectSettings.asset, ProjectSettings/UnityConnectSettings.asset
[Feat]
일반 블럭도 아이템처럼 보조선 반사각 표시 안해주도록 변경
[Fix]
게임 보드 밖에 아이템 설치 가능하던 문제 해결
=> Feat : Subline reflect | Fix : Item outside gameboard

Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/09. Data/ItemProbability Data.asset
=> Feat : 난이도 수정및 어려운 라운드 추가 | Adjust : 수치 조정

Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/BossBlock.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/ItemManager.cs
=> Fix : moveDown 함수 수정

Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/BossBlock.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/09. Data/ItemProbability Data.asset
=> Fix : 아이템과 프리즘 충돌 버그 수정 | 게임 종료 버그 수정

Assets/MyAsset/03. Script/Manager/BlockManager.cs
=> Fix : 프리즘 설치 버그 수정

Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs
=> Feat : 보스 스테이지 블럭 hp 생성 로직 수정

Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/BossBlock.cs, Assets/MyAsset/03. Script/Entity/EEntityType.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/ItemManager.cs
- MoveDown함수 통합
- 블럭의 충돌관련 로직 전반적 수정
- Block 접근 제한자 수정
=> Refactor : 변수 접근 제한자 수정 | Feat : 함수 수정및 통합

Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/BossBlock.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs
=> Fix : 버그 수정

Assets/MyAsset/01. Scenes/Main Scene.unity, Assets/MyAsset/03. Script/Data/BlockProbabilityData.cs, Assets/MyAsset/03. Script/Data/BlockProbabilityData.cs.meta, Assets/MyAsset/03. Script/Data/ItemProbabilityData.cs, Assets/MyAsset/03. Script/Entity/Block.cs, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/07. Animation/UI/FloatingText/FloatingText.anim, Assets/MyAsset/09. Data/BlockProbabilityData.asset, Assets/MyAsset/09. Data/BlockProbabilityData.asset.meta
[Fix]
런쳐 조작 잘 안되던 문제 해결
[Refactor]
블럭 생성 개수 확률 관련 코드 다른 클래스로 변경
=> Fix : Launcher click | Refactor : Block probability

Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, ProjectSettings/ProjectSettings.asset
=> Adjust : 데미지 공식 수정

Assets/MyAsset/03. Script/Entity/BossBlock.cs, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/09. Data/ItemProbability Data.asset
- 보스 블럭이 일정 턴 이상 생존하면 2칸이 내려오는 기믹 추가
- 밸런스 조절
=> Feat : 보스 블럭 기믹 추가 | Adjust : 밸런스 조정

Assets/MyAsset/03. Script/Entity/Block/Block.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/09. Data/ItemProbability Data.asset, ProjectSettings/ProjectSettings.asset, ProjectSettings/UnityConnectSettings.asset
=> Adjust : 벨런스 조절

Assets/MyAsset/03. Script/Entity/Block/Block.cs, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/09. Data/ItemProbability Data.asset, ProjectSettings/ProjectSettings.asset, ProjectSettings/UnityConnectSettings.asset
=> Refactor : 코드 리펙토링 | Adjust : 게임 밸런스 조절

Assets/MyAsset/03. Script/Entity/Block/BossBlock.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs
=> ReFactor : 코드 리펙토링

Assets/MyAsset/03. Script/Manager/BlockManager.cs
=> Fix : 오타 수정

Assets/MyAsset/03. Script/Data/BlockProbabilityData.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/09. Data/BlockProbabilityData.asset
=> Fix : Block probability

Assets/MyAsset/01. Scenes/Main Scene.unity, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/04. Prefab/Block/Block.prefab, Assets/MyAsset/04. Prefab/Block/BlockParticle.prefab, Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
[Fix]
블럭이랑 벽 사이 틈으로 레이저 들어가던 문제 해결
=> Fix : Gap block and wall

Assets/MyAsset/03. Script/Manager/BlockManager.cs
=> Fix : 코드 수정이 적용 안된부분 다시 수정

Assets/MyAsset/03. Script/Manager/BlockManager.cs
=> Feat : 블럭 스테이지기반 HP생성 가중치 추가

Assets/MyAsset/03. Script/Entity/Block/Block.cs, Assets/MyAsset/03. Script/Entity/Energy.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Entity/Wall.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/LaserManager.cs, Assets/MyAsset/04. Prefab/Block/Block.prefab, Assets/MyAsset/04. Prefab/Block/BlockParticle.prefab, Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
=> Refactor : 안 쓰는 코드및 변수 제거

Assets/MyAsset/03. Script/Controller/BlockParticleController.cs, Assets/MyAsset/03. Script/Controller/ToolbarController.cs, Assets/MyAsset/03. Script/Entity/Block/Block.cs, Assets/MyAsset/03. Script/Manager/BlockManager.cs, Assets/MyAsset/03. Script/Manager/GameManager.cs, Assets/MyAsset/03. Script/Manager/LaserManager.cs, Assets/MyAsset/03. Script/Manager/ObjectPoolManager.cs, Assets/MyAsset/03. Script/UI/Controller/FloatingTextController.cs, Assets/MyAsset/04. Prefab/Block/Block.prefab, Assets/MyAsset/04. Prefab/Block/BossBlock.prefab
[Refactor]
블럭 내리는 함수 코루틴에서 일반 함수로 변경
오브젝트 풀링 Register함수 Register + Generate함수로 통합
=> Refactor : Block movedown, Object pool

Assets/MyAsset/03. Script/Manager/LaserManager.cs, ProjectSettings/ProjectSettings.asset
=> Fix : LaserManager 버그

Assets/MyAsset/03. Script/Entity/Block/Block.cs, Assets/MyAsset/03. Script/Entity/Interface/ICollisionable.cs, Assets/MyAsset/03. Script/Entity/Item/InstalledItem/InstalledItem.cs, Assets/MyAsset/03. Script/Entity/Laser.cs, Assets/MyAsset/03. Script/Entity/Wall.cs
- wating 삭제
- GetDamage매개변수 삭제
=> Refactor : 안쓰는 함수및 변수 삭제

Assets/MyAsset/03. Script/Manager/GameSettingManager.cs, Assets/MyAsset/03. Script/ThirdParty/AdaptiveBanner.cs, ProjectSettings/ProjectSettings.asset
=> Fix : Screen bug
